// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SpotifyCredential struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                string             `json:"user_id"`
	AccessToken           string             `json:"access_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenEncrypted string             `json:"refresh_token_encrypted"`
	Scopes                string             `json:"scopes"`
	LastRefreshedAt       pgtype.Timestamptz `json:"last_refreshed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
