// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parties.sql

package sqlc

import (
	"context"
)

const createParty = `-- name: CreateParty :one

INSERT INTO parties (id, host_user_id, name, settings)
VALUES ($1, $2, $3, $4)
RETURNING id, host_user_id, name, settings, is_active, created_at, updated_at
`

type CreatePartyParams struct {
	ID         string `json:"id"`
	HostUserID string `json:"host_user_id"`
	Name       string `json:"name"`
	Settings   []byte `json:"settings"`
}

// Party queries.
// Table: parties (created by infra/migrations/20260512113057_add_parties_queue_tracks_user_votes.sql)
// One row per party. The id is a 6-character alphanumeric short code generated
// server-side. The host_user_id maps to the JWT sub claim (Better-Auth user id).
func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty,
		arg.ID,
		arg.HostUserID,
		arg.Name,
		arg.Settings,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Name,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParty = `-- name: GetParty :one
SELECT id, host_user_id, name, settings, is_active, created_at, updated_at FROM parties WHERE id = $1
`

func (q *Queries) GetParty(ctx context.Context, id string) (Party, error) {
	row := q.db.QueryRow(ctx, getParty, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Name,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
