// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteSpotifyCredentialsByUserID(ctx context.Context, userID string) error
	GetSpotifyCredentialsByUserID(ctx context.Context, userID string) (SpotifyCredential, error)
	// Spotify credentials queries.
	// Table: spotify_credentials (created by infra/migrations/20260510191527_add_spotify_credentials.sql)
	// One row per authenticated host user. The refresh token is stored AES-GCM
	// encrypted; only the ciphertext (base64 text) is persisted here.
	UpsertSpotifyCredentials(ctx context.Context, arg UpsertSpotifyCredentialsParams) (SpotifyCredential, error)
}

var _ Querier = (*Queries)(nil)
