// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue_tracks.sql

package sqlc

import (
	"context"
)

const listQueueTracksByParty = `-- name: ListQueueTracksByParty :many

SELECT party_id, provider, provider_track_id, vote_count, order_idx, is_fallback, added_at
FROM queue_tracks
WHERE party_id = $1
ORDER BY order_idx ASC, added_at ASC
`

// Queue track queries.
// Table: queue_tracks (created by infra/migrations/20260512113057_add_parties_queue_tracks_user_votes.sql)
// One row per unique (party_id, provider, provider_track_id) combination.
// order_idx drives the playback queue order; tiebreaker is added_at ASC.
func (q *Queries) ListQueueTracksByParty(ctx context.Context, partyID string) ([]QueueTrack, error) {
	rows, err := q.db.Query(ctx, listQueueTracksByParty, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueTrack
	for rows.Next() {
		var i QueueTrack
		if err := rows.Scan(
			&i.PartyID,
			&i.Provider,
			&i.ProviderTrackID,
			&i.VoteCount,
			&i.OrderIdx,
			&i.IsFallback,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
