// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spotify_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSpotifyCredentialsByUserID = `-- name: DeleteSpotifyCredentialsByUserID :exec
DELETE FROM spotify_credentials
WHERE user_id = $1
`

func (q *Queries) DeleteSpotifyCredentialsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteSpotifyCredentialsByUserID, userID)
	return err
}

const getSpotifyCredentialsByUserID = `-- name: GetSpotifyCredentialsByUserID :one
SELECT id, user_id, access_token, access_token_expires_at, refresh_token_encrypted, scopes, last_refreshed_at, created_at, updated_at
FROM spotify_credentials
WHERE user_id = $1
`

func (q *Queries) GetSpotifyCredentialsByUserID(ctx context.Context, userID string) (SpotifyCredential, error) {
	row := q.db.QueryRow(ctx, getSpotifyCredentialsByUserID, userID)
	var i SpotifyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenEncrypted,
		&i.Scopes,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpotifyCredentials = `-- name: UpsertSpotifyCredentials :one

INSERT INTO spotify_credentials (
    user_id,
    access_token,
    access_token_expires_at,
    refresh_token_encrypted,
    scopes,
    last_refreshed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (user_id) DO UPDATE SET
    access_token            = EXCLUDED.access_token,
    access_token_expires_at = EXCLUDED.access_token_expires_at,
    refresh_token_encrypted = EXCLUDED.refresh_token_encrypted,
    scopes                  = EXCLUDED.scopes,
    last_refreshed_at       = EXCLUDED.last_refreshed_at,
    updated_at              = now()
RETURNING id, user_id, access_token, access_token_expires_at, refresh_token_encrypted, scopes, last_refreshed_at, created_at, updated_at
`

type UpsertSpotifyCredentialsParams struct {
	UserID                string             `json:"user_id"`
	AccessToken           string             `json:"access_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenEncrypted string             `json:"refresh_token_encrypted"`
	Scopes                string             `json:"scopes"`
	LastRefreshedAt       pgtype.Timestamptz `json:"last_refreshed_at"`
}

// Spotify credentials queries.
// Table: spotify_credentials (created by infra/migrations/20260510191527_add_spotify_credentials.sql)
// One row per authenticated host user. The refresh token is stored AES-GCM
// encrypted; only the ciphertext (base64 text) is persisted here.
func (q *Queries) UpsertSpotifyCredentials(ctx context.Context, arg UpsertSpotifyCredentialsParams) (SpotifyCredential, error) {
	row := q.db.QueryRow(ctx, upsertSpotifyCredentials,
		arg.UserID,
		arg.AccessToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenEncrypted,
		arg.Scopes,
		arg.LastRefreshedAt,
	)
	var i SpotifyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenEncrypted,
		&i.Scopes,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
