// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package sqlc

import (
	"context"
)

const countVotesForTrack = `-- name: CountVotesForTrack :one
SELECT COUNT(*)::integer AS vote_count
FROM user_votes
WHERE party_id = $1
  AND provider = $2
  AND provider_track_id = $3
`

type CountVotesForTrackParams struct {
	PartyID         string `json:"party_id"`
	Provider        string `json:"provider"`
	ProviderTrackID string `json:"provider_track_id"`
}

func (q *Queries) CountVotesForTrack(ctx context.Context, arg CountVotesForTrackParams) (int32, error) {
	row := q.db.QueryRow(ctx, countVotesForTrack, arg.PartyID, arg.Provider, arg.ProviderTrackID)
	var vote_count int32
	err := row.Scan(&vote_count)
	return vote_count, err
}

const deleteVote = `-- name: DeleteVote :exec
DELETE FROM user_votes
WHERE party_id = $1
  AND provider = $2
  AND provider_track_id = $3
  AND user_id = $4
`

type DeleteVoteParams struct {
	PartyID         string `json:"party_id"`
	Provider        string `json:"provider"`
	ProviderTrackID string `json:"provider_track_id"`
	UserID          string `json:"user_id"`
}

func (q *Queries) DeleteVote(ctx context.Context, arg DeleteVoteParams) error {
	_, err := q.db.Exec(ctx, deleteVote,
		arg.PartyID,
		arg.Provider,
		arg.ProviderTrackID,
		arg.UserID,
	)
	return err
}

const insertVote = `-- name: InsertVote :exec

INSERT INTO user_votes (party_id, provider, provider_track_id, user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertVoteParams struct {
	PartyID         string `json:"party_id"`
	Provider        string `json:"provider"`
	ProviderTrackID string `json:"provider_track_id"`
	UserID          string `json:"user_id"`
}

// User vote queries.
// Table: user_votes (created by infra/migrations/20260512113057_add_parties_queue_tracks_user_votes.sql)
// One row per (party_id, provider, provider_track_id, user_id); PK ensures idempotency.
func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) error {
	_, err := q.db.Exec(ctx, insertVote,
		arg.PartyID,
		arg.Provider,
		arg.ProviderTrackID,
		arg.UserID,
	)
	return err
}
