// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthResponseDb.
const (
	HealthResponseDbDown HealthResponseDb = "down"
	HealthResponseDbOk   HealthResponseDb = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDb enum.
func (e HealthResponseDb) Valid() bool {
	switch e {
	case HealthResponseDbDown:
		return true
	case HealthResponseDbOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Db     HealthResponseDb     `json:"db"`
	Status HealthResponseStatus `json:"status"`

	// Version API version (semver)
	Version *string `json:"version,omitempty"`
}

// HealthResponseDb defines model for HealthResponse.Db.
type HealthResponseDb string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Role  *string              `json:"role,omitempty"`

	// UserId Subject claim from the JWT (Neon Auth user ID)
	UserId string `json:"user_id"`
}

// SpotifyTokenExchangeRequest defines model for SpotifyTokenExchangeRequest.
type SpotifyTokenExchangeRequest struct {
	// Code The one-time Spotify OAuth authorization code from the redirect URL
	Code string `json:"code"`

	// RedirectUri The redirect URI that was sent to Spotify during the authorization request
	RedirectUri string `json:"redirectUri"`
}

// SpotifyTokenExchangeResponse defines model for SpotifyTokenExchangeResponse.
type SpotifyTokenExchangeResponse struct {
	// AccessToken Spotify OAuth access token (valid approximately one hour)
	AccessToken string `json:"accessToken"`

	// ExpiresIn Seconds until the access token expires
	ExpiresIn int `json:"expiresIn"`

	// Scopes Space-delimited Spotify OAuth scopes granted
	Scopes string `json:"scopes"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// PostSpotifyTokenJSONRequestBody defines body for PostSpotifyToken for application/json ContentType.
type PostSpotifyTokenJSONRequestBody = SpotifyTokenExchangeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the authenticated user's identity claims
	// (GET /api/me)
	GetMe(c *gin.Context)
	// Exchange a Spotify authorization code for an access token
	// (POST /api/spotify/token)
	PostSpotifyToken(c *gin.Context)
	// Liveness and DB connectivity check
	// (GET /healthz)
	GetHealth(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// PostSpotifyToken operation middleware
func (siw *ServerInterfaceWrapper) PostSpotifyToken(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSpotifyToken(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/api/spotify/token", wrapper.PostSpotifyToken)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse ErrorResponse

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyTokenRequestObject struct {
	Body *PostSpotifyTokenJSONRequestBody
}

type PostSpotifyTokenResponseObject interface {
	VisitPostSpotifyTokenResponse(w http.ResponseWriter) error
}

type PostSpotifyToken200JSONResponse SpotifyTokenExchangeResponse

func (response PostSpotifyToken200JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken400JSONResponse ErrorResponse

func (response PostSpotifyToken400JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken401JSONResponse ErrorResponse

func (response PostSpotifyToken401JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken500JSONResponse ErrorResponse

func (response PostSpotifyToken500JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken502JSONResponse ErrorResponse

func (response PostSpotifyToken502JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse ErrorResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Return the authenticated user's identity claims
	// (GET /api/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Exchange a Spotify authorization code for an access token
	// (POST /api/spotify/token)
	PostSpotifyToken(ctx context.Context, request PostSpotifyTokenRequestObject) (PostSpotifyTokenResponseObject, error)
	// Liveness and DB connectivity check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *gin.Context) {
	var request GetMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSpotifyToken operation middleware
func (sh *strictHandler) PostSpotifyToken(ctx *gin.Context) {
	var request PostSpotifyTokenRequestObject

	var body PostSpotifyTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSpotifyToken(ctx, request.(PostSpotifyTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSpotifyToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(PostSpotifyTokenResponseObject); ok {
		if err := validResponse.VisitPostSpotifyTokenResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFdbb9u4Ev4rA54DND1QZLc9C3T1lrTZrbtpGuSyfegGAUOOLTYSqZIjJ27h/74YSrItW70s0Ab7EjjS",
	"cOaby/cN9VkoV1bOoqUgss8iqBxLGX8eee/8GYbK2YD8oPKuQk8G42vldHyqMShvKjLOiky8kSo3Fvc9",
	"Si1vCgRkLxCNE0GLCkUmAnljZ2KZiBJDkLMBP6/qUtptL531jqNlIjx+rI1HLbL3oo3WmV+t7N3NB1TE",
	"gV+hLCj/cnb6hv+irUt26G5FIrS7sxu+1kkEklSHLfshwzn6ENPbzvbgdALtS9gLWM7RP/5mlm3YhLEO",
	"pfgGv5weltIU/GPqfClJZO2TAdDeFdHBzos6oL82ejeb8zpiAFVIU8LUuxIoR3j97gL2TtBZOKgpBz4O",
	"k5ffzrOLM5TjeeXITBcX7hbt0b3KpZ3hGX6sMdD3TuxFjuAs7pMpEVp/8DZClDXlzptPkk3jDK+z8aiN",
	"5ywvz44Hy9a+v/RmOOaGgwlQLgnuZICAloDcCoiu2WGM2Efj2yy/kwubcL6/kF8aH6kUhhCNB9rfr2E0",
	"BWJb2JvLwmiQVeXdvSklYbHg4kPu6qGJTwTeV8ZjmAzFQeWsDlBbMkVToc1Y7cm1U2MJZ+gjY5WrWp5v",
	"QZcK9zUWpjSEemscmlMw89IS6m9WfrNIm4mswu/2gaGhqr2hxTkLcYPxBqVHzxDW//3W8fb1uwuWgF4a",
	"a5LtHSIR+n3+5zEzMIU/uQWSs5sbCa/f/XEOkuDk6O3J9cHlxatrfnJ9eXacRqAMQmRt0HXKOVEllozX",
	"2KnbLeRpLgPC8/1fIdxigeRsCqM8au4nqOqbwqgERrIyo/9BW7MAa9hNuIhXJKIwCtsxtDLCOa8DSWPj",
	"argMCMeNBcyfpGORiNoXIhNpOkrT0fHkxdHJ+VFaam48GWI1Ey+8u9MXtUU4OJ2IDWUW43ScjtnUVWhl",
	"ZUQmnqWN20pSHhsSgZcR0Ayj0DA5Ii8nWmTid6Q3DekaAsVDT8fjRoQsoY2HZFUVRsVjow+h2QvN/uVf",
	"//U4FZn4z2i9oEftdh5tSHtsQr/4l6ysRqMlQwvAe/JScb9X2rUuLyf6//GTHwasf2cYwHbYhG4oWpoQ",
	"WN2cB2OjNPQoILL3/eF/f7W8SkSoy1L6hcjEGVLt7UocOWEVJ5tXxqOwrkHcRFEK5CwwN7s34ooDxn6G",
	"husj6lStcs0S2VrVSmFFIQYNufO0X5j5jlQMbA5pdU/zE8BWZ6OzEu4M5Z2bRysVs7pyxlICaJVfdJE9",
	"Tj2GvDFKou+KRzhQAOUxZicLXid+jn4/GI0pNOUKu1LJx0skqSXJFC62/YMJYHGOHnz0gJo3FHtRhUFL",
	"6V8san0KnLpAmztFNNqIgQ6dXvywefva/l/2BZl8jcufyMmvbtABJnQDs7W0moMaQh2fT+uiWDQsHT8c",
	"S9sSwo3TC+7+BlFzGTqywtRgocO/T0MS8ctDVmtiCb2VRcu29mNlryUsC4Dz8PIQptIUtcfHDcCnDwew",
	"G7W+pKzZLG2D+Z+pbzfkIFfiN3Rhdp79b075hg63otvKcHtB+Npebb7bfuZu3foyHCpn02YTQLL2R/nU",
	"WKHVaJXBANKzgkqV8wWl6fazB+z2Cl5dwU1NIEF5w6uxWMOMtI5ftFs977X42MzRct84xZeHoJy1qMjM",
	"41LNUd1u9JI3CDcy+mMIIY5QH9yxa2DMV9c0vkpmo1HBL3IXKHs+fj4WPGqt48/D+XG4iCvvRqK9HEYc",
	"y2Rnce/cECDeXVfnVneC3bP95d4Kj7RyhiX3c+WiG+fl1fLvAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
