// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthResponseDb.
const (
	HealthResponseDbDown HealthResponseDb = "down"
	HealthResponseDbOk   HealthResponseDb = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDb enum.
func (e HealthResponseDb) Valid() bool {
	switch e {
	case HealthResponseDbDown:
		return true
	case HealthResponseDbOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// CreatePartyRequest defines model for CreatePartyRequest.
type CreatePartyRequest struct {
	// Name Display name for the party (non-empty, whitespace-trimmed)
	Name string `json:"name"`

	// Settings Opaque party settings blob stored verbatim as JSONB
	Settings *map[string]interface{} `json:"settings,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Db     HealthResponseDb     `json:"db"`
	Status HealthResponseStatus `json:"status"`

	// Version API version (semver)
	Version *string `json:"version,omitempty"`
}

// HealthResponseDb defines model for HealthResponse.Db.
type HealthResponseDb string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ListQueueTracksResponse defines model for ListQueueTracksResponse.
type ListQueueTracksResponse struct {
	// Tracks Queue tracks ordered by order_idx ASC, added_at ASC
	Tracks []QueueTrack `json:"tracks"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Role  *string              `json:"role,omitempty"`

	// UserId Subject claim from the JWT (Neon Auth user ID)
	UserId string `json:"user_id"`
}

// Party defines model for Party.
type Party struct {
	// CreatedAt ISO 8601 creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// HostUserId JWT sub claim of the party host
	HostUserId string `json:"hostUserId"`

	// Id 6-character alphanumeric party short code
	Id string `json:"id"`

	// IsActive Whether the party is currently active
	IsActive bool `json:"isActive"`

	// Name Display name of the party
	Name string `json:"name"`

	// Settings Opaque party settings blob
	Settings map[string]interface{} `json:"settings"`

	// ShortId Alias for id; redundant field for frontend compatibility
	ShortId string `json:"shortId"`

	// UpdatedAt ISO 8601 last-updated timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// QueueTrack defines model for QueueTrack.
type QueueTrack struct {
	// AddedAt ISO 8601 timestamp when the track was added to the queue
	AddedAt time.Time `json:"addedAt"`

	// IsFallback Whether this track was added as a fallback suggestion
	IsFallback bool `json:"isFallback"`

	// OrderIdx Position in the queue; lower values play first
	OrderIdx  int64          `json:"orderIdx"`
	Reference TrackReference `json:"reference"`

	// VoteCount Number of votes this track has received
	VoteCount int `json:"voteCount"`
}

// SpotifyTokenExchangeRequest defines model for SpotifyTokenExchangeRequest.
type SpotifyTokenExchangeRequest struct {
	// Code The one-time Spotify OAuth authorization code from the redirect URL
	Code string `json:"code"`

	// RedirectUri The redirect URI that was sent to Spotify during the authorization request
	RedirectUri string `json:"redirectUri"`
}

// SpotifyTokenExchangeResponse defines model for SpotifyTokenExchangeResponse.
type SpotifyTokenExchangeResponse struct {
	// AccessToken Spotify OAuth access token (valid approximately one hour)
	AccessToken string `json:"accessToken"`

	// ExpiresIn Seconds until the access token expires
	ExpiresIn int `json:"expiresIn"`

	// Scopes Space-delimited Spotify OAuth scopes granted
	Scopes string `json:"scopes"`
}

// TrackReference defines model for TrackReference.
type TrackReference struct {
	// Id Provider-specific track identifier
	Id string `json:"id"`

	// Provider Music provider identifier (e.g. "spotify")
	Provider string `json:"provider"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreatePartyJSONRequestBody defines body for CreateParty for application/json ContentType.
type CreatePartyJSONRequestBody = CreatePartyRequest

// PostSpotifyTokenJSONRequestBody defines body for PostSpotifyToken for application/json ContentType.
type PostSpotifyTokenJSONRequestBody = SpotifyTokenExchangeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the authenticated user's identity claims
	// (GET /api/me)
	GetMe(c *gin.Context)
	// Create a new party
	// (POST /api/parties)
	CreateParty(c *gin.Context)
	// Get party metadata by short code
	// (GET /api/parties/{partyId})
	GetParty(c *gin.Context, partyId string)
	// List the ordered queue for a party
	// (GET /api/parties/{partyId}/tracks)
	ListQueueTracks(c *gin.Context, partyId string)
	// Retract the caller's vote for a track in the party queue
	// (DELETE /api/parties/{partyId}/tracks/{provider}/{trackId}/vote)
	RetractVote(c *gin.Context, partyId string, provider string, trackId string)
	// Cast a vote for a track in the party queue
	// (PUT /api/parties/{partyId}/tracks/{provider}/{trackId}/vote)
	CastVote(c *gin.Context, partyId string, provider string, trackId string)
	// Exchange a Spotify authorization code for an access token
	// (POST /api/spotify/token)
	PostSpotifyToken(c *gin.Context)
	// Liveness and DB connectivity check
	// (GET /healthz)
	GetHealth(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// CreateParty operation middleware
func (siw *ServerInterfaceWrapper) CreateParty(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateParty(c)
}

// GetParty operation middleware
func (siw *ServerInterfaceWrapper) GetParty(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "partyId" -------------
	var partyId string

	err = runtime.BindStyledParameterWithOptions("simple", "partyId", c.Param("partyId"), &partyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter partyId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetParty(c, partyId)
}

// ListQueueTracks operation middleware
func (siw *ServerInterfaceWrapper) ListQueueTracks(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "partyId" -------------
	var partyId string

	err = runtime.BindStyledParameterWithOptions("simple", "partyId", c.Param("partyId"), &partyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter partyId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListQueueTracks(c, partyId)
}

// RetractVote operation middleware
func (siw *ServerInterfaceWrapper) RetractVote(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "partyId" -------------
	var partyId string

	err = runtime.BindStyledParameterWithOptions("simple", "partyId", c.Param("partyId"), &partyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter partyId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", c.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId string

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", c.Param("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trackId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RetractVote(c, partyId, provider, trackId)
}

// CastVote operation middleware
func (siw *ServerInterfaceWrapper) CastVote(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "partyId" -------------
	var partyId string

	err = runtime.BindStyledParameterWithOptions("simple", "partyId", c.Param("partyId"), &partyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter partyId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", c.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId string

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", c.Param("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter trackId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CastVote(c, partyId, provider, trackId)
}

// PostSpotifyToken operation middleware
func (siw *ServerInterfaceWrapper) PostSpotifyToken(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSpotifyToken(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/api/parties", wrapper.CreateParty)
	router.GET(options.BaseURL+"/api/parties/:partyId", wrapper.GetParty)
	router.GET(options.BaseURL+"/api/parties/:partyId/tracks", wrapper.ListQueueTracks)
	router.DELETE(options.BaseURL+"/api/parties/:partyId/tracks/:provider/:trackId/vote", wrapper.RetractVote)
	router.PUT(options.BaseURL+"/api/parties/:partyId/tracks/:provider/:trackId/vote", wrapper.CastVote)
	router.POST(options.BaseURL+"/api/spotify/token", wrapper.PostSpotifyToken)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse ErrorResponse

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePartyRequestObject struct {
	Body *CreatePartyJSONRequestBody
}

type CreatePartyResponseObject interface {
	VisitCreatePartyResponse(w http.ResponseWriter) error
}

type CreateParty201JSONResponse Party

func (response CreateParty201JSONResponse) VisitCreatePartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateParty400JSONResponse ErrorResponse

func (response CreateParty400JSONResponse) VisitCreatePartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateParty401JSONResponse ErrorResponse

func (response CreateParty401JSONResponse) VisitCreatePartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateParty500JSONResponse ErrorResponse

func (response CreateParty500JSONResponse) VisitCreatePartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPartyRequestObject struct {
	PartyId string `json:"partyId"`
}

type GetPartyResponseObject interface {
	VisitGetPartyResponse(w http.ResponseWriter) error
}

type GetParty200JSONResponse Party

func (response GetParty200JSONResponse) VisitGetPartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetParty404JSONResponse ErrorResponse

func (response GetParty404JSONResponse) VisitGetPartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetParty500JSONResponse ErrorResponse

func (response GetParty500JSONResponse) VisitGetPartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListQueueTracksRequestObject struct {
	PartyId string `json:"partyId"`
}

type ListQueueTracksResponseObject interface {
	VisitListQueueTracksResponse(w http.ResponseWriter) error
}

type ListQueueTracks200JSONResponse ListQueueTracksResponse

func (response ListQueueTracks200JSONResponse) VisitListQueueTracksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListQueueTracks401JSONResponse ErrorResponse

func (response ListQueueTracks401JSONResponse) VisitListQueueTracksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListQueueTracks404JSONResponse ErrorResponse

func (response ListQueueTracks404JSONResponse) VisitListQueueTracksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListQueueTracks500JSONResponse ErrorResponse

func (response ListQueueTracks500JSONResponse) VisitListQueueTracksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RetractVoteRequestObject struct {
	PartyId  string `json:"partyId"`
	Provider string `json:"provider"`
	TrackId  string `json:"trackId"`
}

type RetractVoteResponseObject interface {
	VisitRetractVoteResponse(w http.ResponseWriter) error
}

type RetractVote200JSONResponse QueueTrack

func (response RetractVote200JSONResponse) VisitRetractVoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RetractVote204Response struct {
}

func (response RetractVote204Response) VisitRetractVoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RetractVote401JSONResponse ErrorResponse

func (response RetractVote401JSONResponse) VisitRetractVoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RetractVote404JSONResponse ErrorResponse

func (response RetractVote404JSONResponse) VisitRetractVoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RetractVote500JSONResponse ErrorResponse

func (response RetractVote500JSONResponse) VisitRetractVoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CastVoteRequestObject struct {
	PartyId  string `json:"partyId"`
	Provider string `json:"provider"`
	TrackId  string `json:"trackId"`
}

type CastVoteResponseObject interface {
	VisitCastVoteResponse(w http.ResponseWriter) error
}

type CastVote200JSONResponse QueueTrack

func (response CastVote200JSONResponse) VisitCastVoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CastVote401JSONResponse ErrorResponse

func (response CastVote401JSONResponse) VisitCastVoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CastVote404JSONResponse ErrorResponse

func (response CastVote404JSONResponse) VisitCastVoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CastVote500JSONResponse ErrorResponse

func (response CastVote500JSONResponse) VisitCastVoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyTokenRequestObject struct {
	Body *PostSpotifyTokenJSONRequestBody
}

type PostSpotifyTokenResponseObject interface {
	VisitPostSpotifyTokenResponse(w http.ResponseWriter) error
}

type PostSpotifyToken200JSONResponse SpotifyTokenExchangeResponse

func (response PostSpotifyToken200JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken400JSONResponse ErrorResponse

func (response PostSpotifyToken400JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken401JSONResponse ErrorResponse

func (response PostSpotifyToken401JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken500JSONResponse ErrorResponse

func (response PostSpotifyToken500JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken502JSONResponse ErrorResponse

func (response PostSpotifyToken502JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse ErrorResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Return the authenticated user's identity claims
	// (GET /api/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Create a new party
	// (POST /api/parties)
	CreateParty(ctx context.Context, request CreatePartyRequestObject) (CreatePartyResponseObject, error)
	// Get party metadata by short code
	// (GET /api/parties/{partyId})
	GetParty(ctx context.Context, request GetPartyRequestObject) (GetPartyResponseObject, error)
	// List the ordered queue for a party
	// (GET /api/parties/{partyId}/tracks)
	ListQueueTracks(ctx context.Context, request ListQueueTracksRequestObject) (ListQueueTracksResponseObject, error)
	// Retract the caller's vote for a track in the party queue
	// (DELETE /api/parties/{partyId}/tracks/{provider}/{trackId}/vote)
	RetractVote(ctx context.Context, request RetractVoteRequestObject) (RetractVoteResponseObject, error)
	// Cast a vote for a track in the party queue
	// (PUT /api/parties/{partyId}/tracks/{provider}/{trackId}/vote)
	CastVote(ctx context.Context, request CastVoteRequestObject) (CastVoteResponseObject, error)
	// Exchange a Spotify authorization code for an access token
	// (POST /api/spotify/token)
	PostSpotifyToken(ctx context.Context, request PostSpotifyTokenRequestObject) (PostSpotifyTokenResponseObject, error)
	// Liveness and DB connectivity check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *gin.Context) {
	var request GetMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateParty operation middleware
func (sh *strictHandler) CreateParty(ctx *gin.Context) {
	var request CreatePartyRequestObject

	var body CreatePartyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateParty(ctx, request.(CreatePartyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateParty")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreatePartyResponseObject); ok {
		if err := validResponse.VisitCreatePartyResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetParty operation middleware
func (sh *strictHandler) GetParty(ctx *gin.Context, partyId string) {
	var request GetPartyRequestObject

	request.PartyId = partyId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetParty(ctx, request.(GetPartyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetParty")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetPartyResponseObject); ok {
		if err := validResponse.VisitGetPartyResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListQueueTracks operation middleware
func (sh *strictHandler) ListQueueTracks(ctx *gin.Context, partyId string) {
	var request ListQueueTracksRequestObject

	request.PartyId = partyId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListQueueTracks(ctx, request.(ListQueueTracksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListQueueTracks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListQueueTracksResponseObject); ok {
		if err := validResponse.VisitListQueueTracksResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RetractVote operation middleware
func (sh *strictHandler) RetractVote(ctx *gin.Context, partyId string, provider string, trackId string) {
	var request RetractVoteRequestObject

	request.PartyId = partyId
	request.Provider = provider
	request.TrackId = trackId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RetractVote(ctx, request.(RetractVoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RetractVote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RetractVoteResponseObject); ok {
		if err := validResponse.VisitRetractVoteResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CastVote operation middleware
func (sh *strictHandler) CastVote(ctx *gin.Context, partyId string, provider string, trackId string) {
	var request CastVoteRequestObject

	request.PartyId = partyId
	request.Provider = provider
	request.TrackId = trackId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CastVote(ctx, request.(CastVoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CastVote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CastVoteResponseObject); ok {
		if err := validResponse.VisitCastVoteResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSpotifyToken operation middleware
func (sh *strictHandler) PostSpotifyToken(ctx *gin.Context) {
	var request PostSpotifyTokenRequestObject

	var body PostSpotifyTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSpotifyToken(ctx, request.(PostSpotifyTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSpotifyToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(PostSpotifyTokenResponseObject); ok {
		if err := validResponse.VisitPostSpotifyTokenResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptc9s28v8qO/z/Z2rfyJLipJ2cOvfCdtJGOdf2+aF50Xg8ELkS0ZAAA4By1Iy/+80uQJGSoNhpm1wy",
	"kzeJTAL7hN3fPoDvk1SXlVaonE1G7xOb5lgK/nlkUDg8E8YtzvFtjdbR08roCo2TyGuUKJH+z9CmRlZO",
	"apWMkmfSVoVYAL2FqTbgcoSKCMGO0moPy8otenCbS4e2EinuOSPLErPdpJe4RYXJKLHOSDVL7nqJReek",
	"mjE/kWWSmIjirCOHMzX21mQ4rcTbuuHakIBJoSdgnTaYwRzNRDhZgrDw8uL05LBlrie/Y+qSu7teYvBt",
	"LQ1myeg3r+31xqpe8twYbc7RVlpZ3LRSqrOIlX4RaS4V7hkUmZgUCEhUgBdHzFCitWIWofOiLoVap9Ks",
	"3iC0plLg1iyPKfcCReHy7dplE/oXVV0SQf0m6SWZvlUdWp2zdMLVdm19bOEcjWX11rU9OBtDeAk7Fss5",
	"mt17tQxseyRrTMVjad1/aqzx0oj0jd2uq+P3m1LxZvBvQZsMycEmC//zRmbv4ODiqAciyzC7EY7+SnqJ",
	"dFgysf83OE1Gyf8N2mAchEgctHKRpEF0YYxYbKgZpItp+AtuVwpLIQv6MdWmFC4ZhSeRYzG6YAIbL2rL",
	"em5a5qJmGSAthCxhanTJaPDy1SXsnKBWcFC7HGg7jJ/df5INn5iODFWR6GMcyw7cpnDji1N4+sPwEfAa",
	"ciknS7ROlFXSa82RCYd79CZmklxbd2XRjCPKk5a2ngTl9bQDhLQtRi5mwx/20lwYkTo0IIoqF6ou0ci0",
	"QbdcG7cVN6Q9SJ2cR4DjVY4uxy46SwtpbQwqVyxA+G1LkhOtCxSKaD4A9rvKfg5UTyIOwYaJnctBIYXl",
	"zCSzH8FgVqtMKAdTiUXGz6dGK4cqA4pI4eREFjKuSF1l97pXIazbCws/2sXWIkBmSatZOIoVL+zYtnP6",
	"vU4cdIWOBVIHcjaiiSHsg8ou9YPbHBV7AQMT3ArrERCc5sdvic+DA03an0RRTIJU21xZ2g1u9AOmYS/Y",
	"ejZDy/tirs2IPc7ebfI405a9FKRqpf8RCn2LBuaiqNEC+/9UGo7tpVpSuR+etNykcjhDw3iKUzSoUrwv",
	"C/BpnC9XU4bUDo90rSJHcVKXEzQUgrTIdq2SCwsGU5RzzCISrflaK16XX8dIK6fSWzpHzKkuKu3kdHGp",
	"36B6/i7NhZrh1royXjFd5ghaeQ+BQA9OOYGI2uXayD88itP2NtcYzKShHHR1fhxNauH9lZFxnh0CY3C5",
	"cOxcFpUjT24EyWoiyBxXpTFBywfWYl1xHm7IbcldpClay4sjyXnVhrwUHK2FnbkoZAaiqox+J0vhsFiQ",
	"8SHXtYnW6fiukgbtOMYHU60yC7VysvAW6vIKO6MRYlNdoY2JTn1DhoUsJaHqqip+F8yMUK7r6Fss3zVS",
	"V5El+9g5rIXkhuVjmfzM6LnM0OzZClM5lWkIS5mhcnIq0cQsW4VdkR6itlQGhPcdMrCD/VkfXifW2+V1",
	"cn9ttWTDVch1rBuymNZGusUFwZJXc4LCoCGrt3/91CDfy1eXyXoOb6u+nUN0Ds0e/bFLJWEffiWv4zQ5",
	"lwJevvr3BQgHJ89PT24Ori5f3NCTm6vz4z6fDQlB8M1MW/1y56rkjuSVaqojp5ALi/B0759g32CBTqs+",
	"DHJuc/6Aqp4UMu3BQFRy8A8IBrLQiu3ZsbxJLylkiiHyfFmUXNTWCam4G7uyCMd+Bcwf9YeUe02RjJJ+",
	"f9DvD47HR89PLp73y4yLe+movE6OjL7NLmuFcHA2TjrNUDLsD/tDTlMVKlHJZJQ87nuylXA5HwgL7uuz",
	"GTK2klcyFFEtlPyM7hePMx4zeNP+cOhxl6oe3iSqqpApbxv8bn0r5rPRfbmq02vwIawan6qU4KhuAfjO",
	"cWGbtXDdmpcUfTJ89LcJttqmR2Q79Kw9KpXSWgJ0qhIVo+FKCCSj31ad/7fru+teYuuyFGaRjJJzdLVR",
	"y3xACqfs2dTDfGdbG3B3wOgnqB6mEs+/Sa6JIZ8nVbwBVyptIznfT2uo0lF4GwrkW0moDhbNHM3eDBW5",
	"AWawtZ9oO4k+XEblhgmmuuSaotvJ9F8TWK76WWd+lHigQesOdbb4284zMqG6WwU16iHuNlz97/Mor13E",
	"k/gFhJIbbM0JZloXxcI79fDzOXUwDUx0xh1ex6+pGgy+7Xsf++WFXC/5/nNaa6wcGiWKEDV+nPZxge/d",
	"shuJndhuAnkjtAfveek4u/sQcjfhVAkjSnRoLIuzWbN2YzwyJpC0jlJG00KOksA+WY+fXse06wXE9SdM",
	"I/fEVolOZMIJ77FPPp+HePZKO5jqWn2VHvozuuAUjRVhsj5Heri/DtqpaHDbdQCiRGhBFIVvmm/CoNTo",
	"W7u8H5jJOaog1fYJqk9pnTEqdfc8YpA4MSjeoOnDkqECvmoAHpe24wgWgqCQ39L6UOMJ8FjYqfAiiW1t",
	"WvyQaPw6I3DbWDzilKfhxN62g3AopHWws3ECq9bf/RIzzjc8+Tg8IUfhyNIrbkChLTYyoJ/63Y8ng/dN",
	"Q3o3eM+P6N1cuzAZKtBFZkTjDMtKk9lGIP0MmutWKnWU5oEYGExJ0MyL3MQ2uaQApfd0BUJlsD98Qo8M",
	"gwlmfRhPwziJWxbakRld2XbC+Z1l+jeprv1o6A80mmm1Q1BpQaHkYWVViAX5nmIzNQPK3upig6Wed9sj",
	"b9qogKdE9lZa9Go38+aWlF/oQXR/OIyB27nX7lcy8/8U2Hp/cdYRE6MdcPwFOR40w4lwDy78xaB792Jx",
	"ExX4BVjHlezUhWsiDp9bniE3ffuOCytlUYAM8M6ovu9RdG36oyFID3sQAmH1ioCQsDtihx2OyV3GaBe4",
	"+6CYYCpqi92oo5Cs/BUDR98ORYp0HHfaNTE3aKJtl2LgWwb66jNQgC32mlQUBU9Y2Ft9Egohqjpzi+b2",
	"aT0v9ZKqdh+XWERhUGQLZpiFinZ55bI1yeycnsDR6clPx+OjS3h2Cienly/GJz/vLjNGuIsF14nFFcA/",
	"DP4v4OzqEkRxKxb02taFo8a+Gxev6+HwMf4LHoUc5k+DxfHb9odDnxjaaOSJwc6RsGhhn6V6DFoVix/B",
	"P3vEz55AKhQ7jzQIWpEsu9GBkLDf8sq3vPLBvMJsMfsGyV8/JFO4U0f9p0C4aQ5C6A1cc4EZn34fpClW",
	"zpfiDBp7hZxv3ApGLokJwLrXuz3AcKXKxEoPiYHMd8sLS5VVWirXA1SpWTScDU4N2twv6jHtCo2V1llI",
	"DXIci8I2A3krM2yHFRu3orS9Gc/4cfwKfd9J0Nks6/rwWUVaSFTRkfyZtq57ffyJ5vIfuup/0IB++IlF",
	"2e73jcOs3U/7jd8G+V/7IB92QsASAGgDzw5hKmRRG9+xfD/c/3wCNq62CiltNAv1Z1C3cXIQS/CLfRtD",
	"eKxWvLwDwgF0AwyHi/EP3Ur4T4Q/5Z3y2kfIMXP6Y+aCVs49smdYocpQpRItCEMIKtJcTAr0p/34M572",
	"Ury6gklNmTE10slUFK2YHNb88fTama9N2+ao6NxIxWeH1E8rTJ2c82VyjvwpVnOWlEHoIJkeiRCruI+1",
	"F2O+/Dwhd64aDQYFvci1daOnw6fDhFwtEH4f14/YsVx54xKhSmU5Noveg80bZv5mY7lveRceKZjbO1Zy",
	"7G6+XG0RJNqt2/2IoZDWEV4Rjbmmny0FX5Js7l+tLQLuCSVmWCJ/JRf2N9F0d3333wAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
