// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthResponseDb.
const (
	HealthResponseDbDown HealthResponseDb = "down"
	HealthResponseDbOk   HealthResponseDb = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseDb enum.
func (e HealthResponseDb) Valid() bool {
	switch e {
	case HealthResponseDbDown:
		return true
	case HealthResponseDbOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// CreatePartyRequest defines model for CreatePartyRequest.
type CreatePartyRequest struct {
	// Name Display name for the party (non-empty, whitespace-trimmed)
	Name string `json:"name"`

	// Settings Opaque party settings blob stored verbatim as JSONB
	Settings *map[string]interface{} `json:"settings,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Db     HealthResponseDb     `json:"db"`
	Status HealthResponseStatus `json:"status"`

	// Version API version (semver)
	Version *string `json:"version,omitempty"`
}

// HealthResponseDb defines model for HealthResponse.Db.
type HealthResponseDb string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Role  *string              `json:"role,omitempty"`

	// UserId Subject claim from the JWT (Neon Auth user ID)
	UserId string `json:"user_id"`
}

// Party defines model for Party.
type Party struct {
	// CreatedAt ISO 8601 creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// HostUserId JWT sub claim of the party host
	HostUserId string `json:"hostUserId"`

	// Id 6-character alphanumeric party short code
	Id string `json:"id"`

	// IsActive Whether the party is currently active
	IsActive bool `json:"isActive"`

	// Name Display name of the party
	Name string `json:"name"`

	// Settings Opaque party settings blob
	Settings map[string]interface{} `json:"settings"`

	// ShortId Alias for id; redundant field for frontend compatibility
	ShortId string `json:"shortId"`

	// UpdatedAt ISO 8601 last-updated timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// SpotifyTokenExchangeRequest defines model for SpotifyTokenExchangeRequest.
type SpotifyTokenExchangeRequest struct {
	// Code The one-time Spotify OAuth authorization code from the redirect URL
	Code string `json:"code"`

	// RedirectUri The redirect URI that was sent to Spotify during the authorization request
	RedirectUri string `json:"redirectUri"`
}

// SpotifyTokenExchangeResponse defines model for SpotifyTokenExchangeResponse.
type SpotifyTokenExchangeResponse struct {
	// AccessToken Spotify OAuth access token (valid approximately one hour)
	AccessToken string `json:"accessToken"`

	// ExpiresIn Seconds until the access token expires
	ExpiresIn int `json:"expiresIn"`

	// Scopes Space-delimited Spotify OAuth scopes granted
	Scopes string `json:"scopes"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreatePartyJSONRequestBody defines body for CreateParty for application/json ContentType.
type CreatePartyJSONRequestBody = CreatePartyRequest

// PostSpotifyTokenJSONRequestBody defines body for PostSpotifyToken for application/json ContentType.
type PostSpotifyTokenJSONRequestBody = SpotifyTokenExchangeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the authenticated user's identity claims
	// (GET /api/me)
	GetMe(c *gin.Context)
	// Create a new party
	// (POST /api/parties)
	CreateParty(c *gin.Context)
	// Get party metadata by short code
	// (GET /api/parties/{partyId})
	GetParty(c *gin.Context, partyId string)
	// Exchange a Spotify authorization code for an access token
	// (POST /api/spotify/token)
	PostSpotifyToken(c *gin.Context)
	// Liveness and DB connectivity check
	// (GET /healthz)
	GetHealth(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// CreateParty operation middleware
func (siw *ServerInterfaceWrapper) CreateParty(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateParty(c)
}

// GetParty operation middleware
func (siw *ServerInterfaceWrapper) GetParty(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "partyId" -------------
	var partyId string

	err = runtime.BindStyledParameterWithOptions("simple", "partyId", c.Param("partyId"), &partyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter partyId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetParty(c, partyId)
}

// PostSpotifyToken operation middleware
func (siw *ServerInterfaceWrapper) PostSpotifyToken(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSpotifyToken(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/api/parties", wrapper.CreateParty)
	router.GET(options.BaseURL+"/api/parties/:partyId", wrapper.GetParty)
	router.POST(options.BaseURL+"/api/spotify/token", wrapper.PostSpotifyToken)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse ErrorResponse

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePartyRequestObject struct {
	Body *CreatePartyJSONRequestBody
}

type CreatePartyResponseObject interface {
	VisitCreatePartyResponse(w http.ResponseWriter) error
}

type CreateParty201JSONResponse Party

func (response CreateParty201JSONResponse) VisitCreatePartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateParty400JSONResponse ErrorResponse

func (response CreateParty400JSONResponse) VisitCreatePartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateParty401JSONResponse ErrorResponse

func (response CreateParty401JSONResponse) VisitCreatePartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateParty500JSONResponse ErrorResponse

func (response CreateParty500JSONResponse) VisitCreatePartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPartyRequestObject struct {
	PartyId string `json:"partyId"`
}

type GetPartyResponseObject interface {
	VisitGetPartyResponse(w http.ResponseWriter) error
}

type GetParty200JSONResponse Party

func (response GetParty200JSONResponse) VisitGetPartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetParty404JSONResponse ErrorResponse

func (response GetParty404JSONResponse) VisitGetPartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetParty500JSONResponse ErrorResponse

func (response GetParty500JSONResponse) VisitGetPartyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyTokenRequestObject struct {
	Body *PostSpotifyTokenJSONRequestBody
}

type PostSpotifyTokenResponseObject interface {
	VisitPostSpotifyTokenResponse(w http.ResponseWriter) error
}

type PostSpotifyToken200JSONResponse SpotifyTokenExchangeResponse

func (response PostSpotifyToken200JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken400JSONResponse ErrorResponse

func (response PostSpotifyToken400JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken401JSONResponse ErrorResponse

func (response PostSpotifyToken401JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken500JSONResponse ErrorResponse

func (response PostSpotifyToken500JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostSpotifyToken502JSONResponse ErrorResponse

func (response PostSpotifyToken502JSONResponse) VisitPostSpotifyTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse ErrorResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Return the authenticated user's identity claims
	// (GET /api/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Create a new party
	// (POST /api/parties)
	CreateParty(ctx context.Context, request CreatePartyRequestObject) (CreatePartyResponseObject, error)
	// Get party metadata by short code
	// (GET /api/parties/{partyId})
	GetParty(ctx context.Context, request GetPartyRequestObject) (GetPartyResponseObject, error)
	// Exchange a Spotify authorization code for an access token
	// (POST /api/spotify/token)
	PostSpotifyToken(ctx context.Context, request PostSpotifyTokenRequestObject) (PostSpotifyTokenResponseObject, error)
	// Liveness and DB connectivity check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *gin.Context) {
	var request GetMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateParty operation middleware
func (sh *strictHandler) CreateParty(ctx *gin.Context) {
	var request CreatePartyRequestObject

	var body CreatePartyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateParty(ctx, request.(CreatePartyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateParty")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreatePartyResponseObject); ok {
		if err := validResponse.VisitCreatePartyResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetParty operation middleware
func (sh *strictHandler) GetParty(ctx *gin.Context, partyId string) {
	var request GetPartyRequestObject

	request.PartyId = partyId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetParty(ctx, request.(GetPartyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetParty")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetPartyResponseObject); ok {
		if err := validResponse.VisitGetPartyResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSpotifyToken operation middleware
func (sh *strictHandler) PostSpotifyToken(ctx *gin.Context) {
	var request PostSpotifyTokenRequestObject

	var body PostSpotifyTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSpotifyToken(ctx, request.(PostSpotifyTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSpotifyToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(PostSpotifyTokenResponseObject); ok {
		if err := validResponse.VisitPostSpotifyTokenResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fltbxu5Ef4rA7bAOcXqJXfXQ6p+shP3otSxDb80H1IjoJYjLy+75IaclaML9N+LIXellUTHuSIxGqBf",
	"EklLzvs888z6k8htVVuDhryYfBI+L7CS4eNzh5LwXDpaXuCHBj3xr7WzNTrSGM4YWSH/r9DnTtekrRET",
	"8UL7upRL4Kcwtw6oQKhZEBwYawZY1bTM4K7QhL6WOQ7I6apC9URkgpY1ionw5LS5FatMeCTS5jbok0pp",
	"ViLL854d5BrMdmw4q+WHptPaiYBZaWfgyTpUsEA3k6QrkB5eXZ6dHm2U29lvmJNYrTLh8EOjHSoxeRu9",
	"vdk7lYlj56y7QF9b43E/SrlViSi9lnmhDQ4cSiVnJQKyFAiHE2Go0Ht5m5Dzsqmk2ZXSnd4TtONSq607",
	"nnLuJcqSivu9UzP+F01TsUD7XmRC2TvTk9XLJUlq/M751MEFOh/c2/X28HwK7UM48Fgt0D150MtWbca2",
	"plx8jfe7h5XUJX+YW1dJEpP2l4TRzpZBwN6DxqN7p9W+N5dNsAHyUuoK5s5WoVdevbmCg1O0Bg4bKoCv",
	"w/TFw352elI+hkZO1GbocnVI+8ZNL8/g2S/jpxDOcMBJV+hJVrXINuFQknDAT1IhKayna49umnCevfTN",
	"rHXeznswwddS4lIx/GWQF9LJnNCBLOtCmqZCp/Ou9wvr6N6u0v4wJ71ItNWbAqnAPnZpD3njHBoqlyDj",
	"tbXImbUlSsMyvwAU+84+BuaJREGEwKTyclhq6QNua/V3cKgao6QhmGssVfh97qwhNAp4eEjSM13qtCNN",
	"rR4sr1J6GrQH/3CJ7XSAVmLjWZuKrSrsxbaX/azXB32jU410WVvS8+WVfY/m+GNeSHOL9w7INPRfFQjW",
	"RJeglQdnoddlQ4V1+vfYcHx9AwsOlXYMF9cXJ0n8aZ9fO53W2RMwBSokwZ304NEQkF0bohoWGDRuW+Na",
	"L79wqPTN+fJA3ofDMs/R+3A4gaPbMQxHgfgsHCxkqRXIunb2o64kYbnk4ENhG5ckHPix1g79NKUHc2uU",
	"h8aQLmOE+rramxuh2hDeogvtltu6HZg7pjMBUljqSnMDbLsSb8Gtk4ZQPRj5fpD6jqzV36Q4jse8cZqW",
	"l0z+oo0zlA4dm7D59o+uHV+9uRK72LOZVgdHSIRuwF+e8Cgbwr84BaG9F1rCqzf/vARJcHp8dvru8Prq",
	"5Tv+5d31xckwGMpGMKIGpRuXC6JarNhebeZ2P5DnhfQIzwZ/A/8eSyRrhjAqAnn5HepmVuo8g5Gs9egv",
	"0MbMw8bsqC7YKzJR6hzbMoxwLi4bT1KbwLGuPcJJPAGLp8MxY4YrxUQMh6PhcHQyfX58enk8rBQnnjQx",
	"LRDPnb1TV41BODyfih7FEePheDjmo7ZGI2stJuKnYRRbSypCQoLhca7cYgAabo7Ql4zh4lek17HpYgOF",
	"Sz+OxxGEGK3DJVnXpc7DtdFvPhKsyPn5058dzsVE/Gm0WQpG7UYw6nGkkITt4DO6glZoSNMS8COFgaw2",
	"2LUJLzv68/jpVzNsm3wnbDuKqmOLVtp7RjeebiZAw1YLiMnb7eJ/e7O6yYRvqkq6pZiIC6TGmTU4ssN5",
	"qGzmXj/4TQwCqwlQIHmO82iKT8QNKwz55EndwlttfWJGxh3MgwSDd+1gv9MMceDRLdANbtFwGaCCe3nQ",
	"hgEN4SppN8wwtxX6HQY2/Dcjx3ad9bZCEbEHPR1Ztfxq+UzsnattnGPus9or9a9XUdG7RCWFB9BSBfBN",
	"QNt5U5bLWNTjxyvqNjQwsyow015dF9J3tR05m//fa7lM/PUxozU1hM7Isu2auCT/scaPZdnvxF5vd428",
	"19qjT+HoVK0+h9xdO9XSyQoJnQ/m7BO4fo8n1hvN53hkdNR3Ilr1Yrd/sl5odznFzTccIw/0VoUklSQZ",
	"K/bnx6uQqN5YgrltzHdZob8itUXRRRFmu/vvvfXqI+0cUUew0wPpMM+xpjgoguRBqRd7rDWxxEijttaP",
	"DLCl/EFYFcdaK+aHNaE2qrbaUAZocrfsNDucO/RFPJQF2TWzKU+e0TkMWln6bkZ6zaMvTm6/z9r5ehex",
	"OCG35DO6GuScuCCBl1QbpOSlRpOckufWU3+9+Uaj8nOr6BfNzPE3NuX+eu8KZmd/ihf/P1u/99kKB23D",
	"MgBYBy+OYC512Th8Eg388fEM7EptG1I23SzNf4O2XZGDXINf6t2NdSy/X+U9GG5Bt4Xhdlf9HFGI7+K/",
	"5Zq387Y/Fc6YZu1BMvYH+FRYo1Focs3LimMElXnBu3LM9k+PmO21eU0Ns4ZAQu40bzvlxszQ1uGvFDs5",
	"30rxiV6g4byxiy+OILfGYE56Efa7AvP3vVzyBOFEBnlsQorDndhoxmL9xqAgqiejUckPeOeaPBs/Gwsu",
	"tVbwp7R/rC7YVXQl0RK+YMcq2xvc+0tfeI2yvrdeT/fv9tYeLuz+vNwmmkwp9q9vc4MWt6SRt1hxOawl",
	"dN2wuln9JwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
